### ISSUE TITLE
UPP on Hercules

### ISSUE THREAD

**Issue by BijuThomas-NOAA** [NOAA-EMC/UPP#719]
Wondering if UPP has been tested on Hercules?  I'm trying to test the HAFS on Hercules and got some issues with CRTM. 

The upp build is successful with spack-stack-1.4.0 on Hercules. However, I end up with a segmentation fault error while running.

```
Caught signal 11 (Segmentation fault: address not mapped to object at address 0x20)
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
libc.so.6          00007FF8ED81ED90  Unknown               Unknown  Unknown
hafs_post.x        0000000000EEB8D0  Unknown               Unknown  Unknown
hafs_post.x        0000000000EEB244  Unknown               Unknown  Unknown
hafs_post.x        0000000000BC2753  crtm_forward_modu         389  CRTM_Forward_Module.f90
hafs_post.x        0000000000719E25  calrad_wcloud_           1708  CALRAD_WCLOUD_newcrtm.f
hafs_post.x        00000000006163F6  process_                  127  PROCESS.f
hafs_post.x        000000000056F9AD  MAIN__                    724  WRFPOST.f
```

**Comment by ulmononian** [comment]
@BijuThomas-NOAA can i ask if you built hafs/ran tests as part of the ufs-wm rt suite or as the standalone application? 

for my ufs-wm RT testing on hercules, the `hafs_regional_storm_following_1nest_atm_ocn_debug` test was the only failed hafs test, _but_ this was with spack-stack/1.3.1.

i am not sure if anyone has explicitly tested the upp on hercules.

**Comment by BijuThomas-NOAA** [comment]
@ulmononian I was able to build all HAFS components and ran end-to-end HAFS workflow (without DA) with spack-stack/1.4.0. The issue with DA is due to the failure of the tar command(https://github.com/JCSDA/spack-stack/issues/609). Recently, I noticed a segmentation fault with UPP.

**Comment by ulmononian** [comment]
@BijuThomas-NOAA ok interesting. you could try re-running the end-to-end workflow (with & without DA) with this updated stack: `/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.4.0/envs/unified-env-v2`. we had to revert back to `hdf5@1.14.0`. i am not sure if it will solve any of these issues, but it may be worth a shot.

also, please be sure to follow these prerequisite module load commands before using spack-stack to build or run anything: https://spack-stack.readthedocs.io/en/latest/PreConfiguredSites.html#msu-hercules

**Comment by BijuThomas-NOAA** [comment]
@ulmononian Thanks, Do you have an updated stack on Hercules that I can try?

**Comment by ulmononian** [comment]
sorry @BijuThomas-NOAA!!! i meant to paste the hercules path: `/work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.4.0-hercules/envs/unified-env-v2`. there you go.

**Comment by WenMeng-NOAA** [comment]
@BijuThomas-NOAA Right now, the UPP doesn't have hercules support yet. Do you know if the hpc-stack is installed on Hercules? If yes, please provide the location.

**Comment by BijuThomas-NOAA** [comment]
@WenMeng-NOAA I use spack-stack for building all HAFS components. Please see below to get the spack-stack environment:
```
module purge                                                                                         
module use /work/noaa/epic-ps/role-epic-ps/spack-stack/modulefiles                                   
module load ecflow/5.8.4-hercules                                                                    
module load mysql/8.0.31-hercules                                                                    
module use /work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.4.0-hercules/envs/unified-env/install/modulefiles/Core
module load stack-intel/2021.7.1                                                                     
module load stack-intel-oneapi-mpi/2021.7.1         
```

You may also want to take a look at the modulefile that I use on Hercules to build UPP:

`/work2/noaa/hwrf/save/bthomas/hafsv1_merge_hercules/sorc/hafs_forecast.fd/FV3/upp/modulefiles/hercules.lua`

**Comment by WenMeng-NOAA** [comment]
@BijuThomas-NOAA I don't see module crtm/2.4.0 available, only crtm-fix/2.4.0_emc.

**Comment by BijuThomas-NOAA** [comment]
@WenMeng-NOAA 

`/work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.4.0-hercules/envs/unified-env/install/intel/2021.7.1/crtm-2.4.0-2kt7wsz/lib/libcrtm.a`

**Comment by WenMeng-NOAA** [comment]
@BijuThomas-NOAA Please give me access permission to /work2/noaa/hwrf/save/bthomas/hafsv1_merge_hercules/sorc/hafs_forecast.fd/FV3/upp/modulefiles/hercules.lua

**Comment by BijuThomas-NOAA** [comment]
@WenMeng-NOAA Can you copy this:

/work2/noaa/hwrf/scrub/bthomas/upp/hercules.lua

**Comment by WenMeng-NOAA** [comment]
@

> 

@BijuThomas-NOAA Still permission denied.

**Comment by WenMeng-NOAA** [comment]
@BijuThomas-NOAA I got the same failure as yours when using spack-stack-1.4.0 on Hercules. 
The UPP test with spack-stack-1.3.1 also failed. The UPP can be run successfully without generating simulated satellite products.  I would think the issue might be in crtm/2.4.0 installation or fix files for crtm/2.4.0. All crtm files in my tests are from crtm/2.4.0_emc module at run time.

**Comment by BijuThomas-NOAA** [comment]
@WenMeng-NOAA Thanks for the update.

**Comment by WenMeng-NOAA** [comment]
@BijuThomas-NOAA Please let us know when there are updates in crtm/2.4.0 at the spack-stack on hercules.

**Comment by BijuThomas-NOAA** [comment]
@WenMeng-NOAA Thanks for the tests and updates. Perhaps we have to open an issue at https://github.com/JCSDA/spack-stack/issues

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA Thanks for the tests and updates. Perhaps we have to open an issue at https://github.com/JCSDA/spack-stack/issues

@BijuThomas-NOAA Good idea. Please report this issue. I never see this failure from crtm/2.4.0 at the hpc-stack.

**Comment by WenMeng-NOAA** [comment]
@ulmononian I saw you submitted the PR #[1733](https://github.com/ufs-community/ufs-weather-model/pull/1733) on ufs-weather-model. I tweaked my UPP test case with spack-stack-1.4.0. The building was successful but failed at runtime for MPI server not found as:
```
MPI startup(): PMI server not found. Please set I_MPI_PMI_LIBRARY variable if it is not a singleton case.
```
You may access the build modulefile for hercules at /home/wmeng/stmp2/UPP_hercules/UPP/modulefiles/hercules.lua  and runtime script at /home/wmeng/stmp2/UPP_hercules/UPP/submit_run_post_fv3hafs_hercules.sh. Please let me know if you think some updates are needed.

**Comment by ulmononian** [comment]
@WenMeng-NOAA i think you need to change the primary modulepath to `/work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.4.0-hercules/envs/unified-env-v2/install/modulefiles/Core` (i just fixed this line in the PR). my apologies for that. 

as i reported here: https://github.com/JCSDA/spack-stack/issues/623#issuecomment-1581579294, i was able to build UPP w/ spack-stack/1.4.0 (unified-env-v2) and the run task submitted properly (i.e., no MPI startup() issue), but it failed in crtm as you and @BijuThomas-NOAA initially reported. 

please let me know if switching the module path fixes the MPI startup problem. my guess it that you'll end up hitting the crtm segfault issue as before.

**Comment by ulmononian** [comment]
if using the corrected stack path does not work, you can also try adding `--mpi=pmi2` to your srun command. we need to do this for the fv3.exe in the WM RTs. you may also need to add `export I_MPI_PMI_LIBRARY=/opt/slurm/lib/libpmi2.so` before your srun command. but i did not need to do either of these steps to run the UPP/HAFS test case. just adding it here in case.

**Comment by WenMeng-NOAA** [comment]
@ulmononian Thanks for advising the fix. Now my UPP test case can run through without simulated satellite product generation. But it still failed at routines in crtm module for generating simulated satellite product generation, such as:
```
=================================
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
libc.so.6          000015350E9C9D90  Unknown               Unknown  Unknown
upp.x              0000000000F07B7C  Unknown               Unknown  Unknown
upp.x              0000000000BDF33B  crtm_forward_modu         389  CRTM_Forward_Module.f90
upp.x              0000000000724B78  calrad_wcloud_           1722  CALRAD_WCLOUD_newcrtm.f
upp.x              0000000000612F0A  process_                  128  PROCESS.f
upp.x              000000000056A361  MAIN__                    695  WRFPOST.f
upp.x              0000000000412D1D  Unknown               Unknown  Unknown
libc.so.6          000015350E9B4EB0  Unknown               Unknown  Unknown
libc.so.6          000015350E9B4F60  __libc_start_main     Unknown  Unknown
upp.x              0000000000412C35  Unknown               Unknown  Unknown
srun: error: hercules-06-63: task 52: Exited with exit code 174
```
Do you any other applications might have issues from crtm/2.4.0 at spack-stack beside UPP? From our UPP perspective, we run crtm as a black box and has no much knowledge in debugging crtm code.

**Comment by WenMeng-NOAA** [comment]
@BijuThomas-NOAA There was a new version of spack-stack installed on Hercules (See [here](https://github.com/JCSDA/spack-stack/issues/623)). I tested it in UPP. Now simulated satellite generation is working well. You may access my UPP version at /home/wmeng/stmp2/UPP_hercules/UPP:
```
modulefile: UPP/modulefiles/hercules.lua
driver script for hafs: UPP/submit_run_post_fv3hafs_hercules.sh
```
Please test from you side.

**Comment by BijuThomas-NOAA** [comment]
@WenMeng-NOAA Thank you. I will test it and let you know how it goes.

**Comment by BijuThomas-NOAA** [comment]
@WenMeng-NOAA I tested it on our HAFS system:

I see an error  in one of the grib out files (HURPRS.GrbF00):
/work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-dev-20230717/envs/unified-env/install/intel/2021.9.0/wgrib2-3.1.1-fpehdip/bin/wgrib2 -s 09l.2021082718.hfsa.storm.atm.f000.grb2

1:0:d=2021082718:PRMSL:mean sea level:anl:
2:438530:d=2021082718:REFC:entire atmosphere (considered as a single layer):anl:
3:673274:d=2021082718:GUST:surface:anl:
4:910455:d=2021082718:HGT:2 mb:anl:

*** FATAL ERROR: rd_grib2_msg_seq_file for 09l.2021082718.hfsa.storm.atm.f000.grb2, missing end section ('7777') **

**Comment by WenMeng-NOAA** [comment]
@BijuThomas-NOAA It seems that this rd_grib2_msg_seq_file errors occurred in hafs post processing on Orion too. We might debug it in another UPP issue. Can you test for non F00 forecast hour to ensure the crtm calling issue can be solved with the new spack-stack?

**Comment by BijuThomas-NOAA** [comment]
@WenMeng-NOAA No Segmentation fault which was described at the beginning of issues(719)
BTW, with the executable built on Orion(/work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/modulefiles/stack, 
hpc-intel/2022.1.2, hpc-impi/2022.1.2), I was able to run upp on Hercules successfully.

**Comment by WenMeng-NOAA** [comment]
> I see an error in one of the grib out files (HURPRS.GrbF00):
/work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-dev-20230717/envs/unified-env/install/intel/2021.9.0/wgrib2-3.1.1-fpehdip/bin/wgrib2 -s 09l.2021082718.hfsa.storm.atm.f000.grb2

> 1:0:d=2021082718:PRMSL:mean sea level:anl:

> 2:438530:d=2021082718:REFC:entire atmosphere (considered as a single layer):anl:
> 3:673274:d=2021082718:GUST:surface:anl:
> 4:910455:d=2021082718:HGT:2 mb:anl:
> 
> *** FATAL ERROR: rd_grib2_msg_seq_file for 09l.2021082718.hfsa.storm.atm.f000.grb2, missing end section ('7777') **
@BijuThomas-NOAA You may open a new issue for this.

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA No Segmentation fault which was described at the beginning of issues(719) BTW, with the executable built on Orion(/work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/modulefiles/stack, hpc-intel/2022.1.2, hpc-impi/2022.1.2), I was able to run upp on Hercules successfully.

@BijuThomas-NOAA Can you test with new spack-stack on Hercules? It is installed as:
```
module use /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-dev-20230717/envs/unified-env/install/modulefiles/Core
module load stack-intel/2021.9.0
module load stack-intel-oneapi-mpi/2021.9.0
module load stack-python/3.9.14
module available
```
You may get my modulefiles for Herclues at /home/wmeng/stmp2/UPP_hercules/UPP/modulefiles/hercules.lua
The modules loaded for runtime can be found at /home/wmeng/stmp2/UPP_hercules/UPP/submit_run_post_fv3hafs_hercules.sh

**Comment by BijuThomas-NOAA** [comment]
> 

@WenMeng-NOAA Thanks, I tried with the same modules that you pointed for build/run, and got the same FATAL ERROR:

```
/work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-dev-20230717/envs/unified-env/install/intel/2021.9.0/wgrib2-3.1.1-fpehdip/bin/wgrib2 -s 09l.2021082718.hfsa.storm.atm.f000.grb2
1:0:d=2021082718:PRMSL:mean sea level:anl:
2:438530:d=2021082718:REFC:entire atmosphere (considered as a single layer):anl:
3:673274:d=2021082718:GUST:surface:anl:
4:910455:d=2021082718:HGT:2 mb:anl:
5:1378354:d=2021082718:TMP:2 mb:anl:

*** FATAL ERROR: rd_grib2_msg_seq_file for 09l.2021082718.hfsa.storm.atm.f000.grb2, missing end section ('7777') ***
```

**Comment by WenMeng-NOAA** [comment]
> > 
> 
> @WenMeng-NOAA Thanks, I tried with the same modules that you pointed for build/run, and got the same FATAL ERROR:
> 
> ```
> /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-dev-20230717/envs/unified-env/install/intel/2021.9.0/wgrib2-3.1.1-fpehdip/bin/wgrib2 -s 09l.2021082718.hfsa.storm.atm.f000.grb2
> 1:0:d=2021082718:PRMSL:mean sea level:anl:
> 2:438530:d=2021082718:REFC:entire atmosphere (considered as a single layer):anl:
> 3:673274:d=2021082718:GUST:surface:anl:
> 4:910455:d=2021082718:HGT:2 mb:anl:
> 5:1378354:d=2021082718:TMP:2 mb:anl:
> 
> *** FATAL ERROR: rd_grib2_msg_seq_file for 09l.2021082718.hfsa.storm.atm.f000.grb2, missing end section ('7777') ***
> ```

@BijuThomas-NOAA I would think this grib2 file dumping error is a different issue. You might open a new UPP issue for it. To test crtm issue you reported in this UPP issue, can you test hafs post process with non F00/ana hours, e.g. F003?

**Comment by BijuThomas-NOAA** [comment]
@WenMeng-NOAA I ran for F003 as well, with the same modules that you pointed out for build/run. The output file "HURPRS.GrbF03" has been created, but has _rd_grib2_msg_seq_file_ error. Thanks

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA I ran for F003 as well, with the same modules that you pointed out for build/run. The output file "HURPRS.GrbF03" has been created, but has _rd_grib2_msg_seq_file_ error. Thanks

@BijuThomas-NOAA Please provide your hafs model history files. I can run my test.

**Comment by BijuThomas-NOAA** [comment]
@WenMeng-NOAA It is here:

/work2/noaa/hwrf/scrub/bthomas/hafsv1_develop_Jul13_hfsa_dev/2021082718/09L/forecast/
Here is F003 upp.x test
/work2/noaa/hwrf/scrub/bthomas/hafsv1_develop_Jul13_hfsa_dev/2021082718/09L/atm_post2/post.nest02_2021082721

Thanks

**Comment by WenMeng-NOAA** [comment]
@BijuThomas-NOAA Can you change access permission of these two directories for me?

**Comment by BijuThomas-NOAA** [comment]
@WenMeng-NOAA Sorry, Can you try again? Thanks

**Comment by WenMeng-NOAA** [comment]
@BijuThomas-NOAA I ran the UPP standalone test with your model history files and UPP control file postxconfig-NT.txt from /work2/noaa/hwrf/scrub/bthomas/hafsv1_develop_Jul13_hfsa_dev/2021082718/09L/atm_post2/post.nest02_2021082721. My test was successful. You may access the run directory of my test at /home/wmeng/stmp2/post_hafs_2021082718. The job card is /home/wmeng/stmp2/UPP_hercules/UPP/submit_run_post_fv3hafs_hercules.sh. You may compare the settings of my job card and yours.

**Comment by BijuThomas-NOAA** [comment]
@WenMeng-NOAA Thank you. I will compare your setting and re-run them again.

**Comment by WenMeng-NOAA** [comment]
@BijuThomas-NOAA May I know the status of your UPP testing with new version of spack-stack? If it works, I will submit a PR for adding a new modulefiles for Hercules.

**Comment by BijuThomas-NOAA** [comment]
@WenMeng-NOAA The UPP test within the HAFS system succeded on Hercules with the new version of spack-stack. Thank you. Much appreciated!

**Comment by WenMeng-NOAA** [comment]
@BijuThomas-NOAA Thanks for confirming. I will close this issue and open a new issue for adding new modulefiles for Hercules.

**Comment by WenMeng-NOAA** [comment]
@BijuThomas-NOAA The UPP develop branch was updated with new modulefile for Hercules.
